### ISSUE TITLE
Adjust clouds positioning

### ISSUE THREAD

**Issue by r-mikegester** [r-mikegester/QC-IOSK-DEVS#17]
Positions of clouds should be evenly distributed. Decrease also the size

![Image](https://github.com/r-mikegester/QC-IOSK-DEVS/assets/92847204/cc91fd4a-15dd-47e0-aa53-0eb423b34cc9)

**Comment by JMDGO29** [comment]
Clean Version

![Image](https://github.com/r-mikegester/QC-IOSK-DEVS/assets/92847204/e93ad177-7ecd-40ee-a9fe-ad18ef49d0a8)
