### ISSUE TITLE
Green Benches from Open Ground

### ISSUE THREAD

**Issue by r-mikegester** [r-mikegester/QC-IOSK-DEVS#24]
Render

![Image](https://github.com/r-mikegester/QC-IOSK-DEVS/assets/92847204/17cd49f3-33ff-4bc5-a40a-5b8e3c13f53b)

**Comment by callmezai101207** [comment]
![Image](https://github.com/r-mikegester/QC-IOSK-DEVS/assets/125576823/1ea7376f-2cc4-4128-83e2-0fc6985dcb34)
