### ISSUE TITLE
Korphil Building

### ISSUE THREAD

**Issue by r-mikegester** [r-mikegester/QC-IOSK-DEVS#32]
Render this model

https://drive.google.com/drive/folders/1uPRsRlHDNuoo1HLzdiAkgUeBTMPtiIac?usp=sharing

![Image](https://github.com/r-mikegester/QC-IOSK-DEVS/assets/92847204/59d222be-8a8a-448c-a4d3-3c33204410f1)

**Comment by DocHaruu** [comment]
![Image](https://github.com/r-mikegester/QC-IOSK-DEVS/assets/126402008/f317e501-e2f0-4037-8e60-99ed31d8acd5)
