### ISSUE TITLE
Render trash bins

### ISSUE THREAD

**Issue by r-mikegester** [r-mikegester/QC-IOSK-DEVS#36]
Render or look 3d similar to this

![Image](https://github.com/r-mikegester/QC-IOSK-DEVS/assets/92847204/c1419e0d-279c-47b8-ae35-9a980dd720cc)

**Comment by Nenhel** [comment]
https://drive.google.com/drive/folders/1QW3dXq2eNDS08D3eVFNEbAkJB0Tgs1mn?usp=drive_link



![Image](https://github.com/r-mikegester/QC-IOSK-DEVS/assets/151374579/8f06e7d3-b345-44ce-a37c-2fac26146a8a)
