### ISSUE TITLE
Revision of clouds

### ISSUE THREAD

**Issue by r-mikegester** [r-mikegester/QC-IOSK-DEVS#37]
Revise the current clouds or make new ones.

The volume of clouds should be even when rotated.

![Image](https://github.com/r-mikegester/QC-IOSK-DEVS/assets/92847204/3b0510a9-815a-4df2-ba02-2a13a37f9d4c)

The volume somewhat close to this

![Image](https://github.com/r-mikegester/QC-IOSK-DEVS/assets/92847204/59c2d615-24c4-413f-8867-98d298d712ce)

**Comment by Nenhel** [comment]
https://drive.google.com/drive/folders/151RkQgtL6KnsBNo8vn38okcO5XOE2z9U?usp=drive_link



![Image](https://github.com/r-mikegester/QC-IOSK-DEVS/assets/151374579/90657290-7da5-4b31-99c9-221bb8ebe1c3)
