### ISSUE TITLE
Render metal fence/s

### ISSUE THREAD

**Issue by r-mikegester** [r-mikegester/QC-IOSK-DEVS#39]
Render metal fences at least 2 kinds or look 4d models similar to this

![Image](https://github.com/r-mikegester/QC-IOSK-DEVS/assets/92847204/5be1b623-440c-4f8e-b302-d4d09c1e0f6e)

**Comment by Nenhel** [comment]
https://drive.google.com/drive/folders/1YPdBJLkXMRX1P-abJA4bwo8oNgaQJx79?usp=drive_link

![Metal_fences](https://github.com/r-mikegester/QC-IOSK-DEVS/assets/151374579/c3b7b58f-1b05-459f-a6c5-825c0d9e4ee2)
