### ISSUE TITLE
Entrance shed

### ISSUE THREAD

**Issue by r-mikegester** [r-mikegester/QC-IOSK-DEVS#40]
Render. See the references here:

https://drive.google.com/drive/folders/1JDjOqOx_-sfdN7Gv2U-A6j7yBLOSeF9X?usp=sharing

![Image](https://github.com/r-mikegester/QC-IOSK-DEVS/assets/92847204/95d7eb48-e941-49f6-8810-cd5d02f3c5bd)

**Comment by Bokie09** [comment]
![Image](https://github.com/r-mikegester/QC-IOSK-DEVS/assets/128199599/5443a8ee-5857-4231-b8d0-75b2b15423d0)

**Comment by r-mikegester** [comment]
Pa ikot yan pre di sya patulis sa dulo check mo yung iba pang pic sa google drive

**Comment by Bokie09** [comment]
Ano yung mali yung sa daanan ba? Sent from my phone-------- Original message --------From: Mike Gester ***@***.***>Date: Fri, 8 Dec 2023, 2:22 pmTo: r-mikegester/QC-IOSK-DEVS ***@***.***>Cc: "Viñas, Christopher V." ***@***.***>, Comment ***@***.***>Subject: Re: [r-mikegester/QC-IOSK-DEVS] Entrance shed (Issue #40)
Pa ikot yan pre di sya patulis sa dulo check mo yung iba pang pic sa google drive

**Comment by Bokie09** [comment]
![Image](https://github.com/r-mikegester/QC-IOSK-DEVS/assets/128199599/a6ec112a-229e-4ad6-8fdf-dd12395e9af6)
