### ISSUE TITLE
Urban Farming (Open Ground)

### ISSUE THREAD

**Issue by JMDGO29** [r-mikegester/QC-IOSK-DEVS#46]
Render this model

https://drive.google.com/drive/folders/1zJXYXFnonZpe2I4gY5bplEyy6ik_fsy4?usp=sharing

**Comment by sainttdriaaan23** [comment]
https://drive.google.com/drive/u/1/folders/1T91x6j7l5Y0x4mnxlZ7ALnBRX4udzNNb

uploaded na
