### ISSUE TITLE
REVISED BAUTISTA BUILDING

### ISSUE THREAD

**Issue by JMDGO29** [r-mikegester/QC-IOSK-DEVS#48]
Finish the design (top part of the building)

![Image](https://github.com/r-mikegester/QC-IOSK-DEVS/assets/92847204/072146f0-0492-414e-8ac3-48ffaef04c2b)

**Comment by callmezai101207** [comment]
![Image](https://github.com/r-mikegester/QC-IOSK-DEVS/assets/125576823/c6f5c4d3-2f8b-46e2-a23d-f6c03a6de0ee)
