### ISSUE TITLE
Revision of Belmonte building

### ISSUE THREAD

**Issue by JMDGO29** [r-mikegester/QC-IOSK-DEVS#49]
Finish the rooftop

![Image](https://github.com/r-mikegester/QC-IOSK-DEVS/assets/92847204/bb9433ae-6775-4e09-8f38-91c480addad3)

**Comment by callmezai101207** [comment]
![Image](https://github.com/r-mikegester/QC-IOSK-DEVS/assets/125576823/35c021c7-9c92-4f76-848c-5014187cb682)
